server:
  port: 8080
  #ssl:
    #服务端
    #key-store: classpath:ssl/server.p12
    #key-store-password: 123456
    #key-store-type: JKS
    #key-alias: tomcat
    #客户端
    #trust-store: classpath:ssl/server.p12
    #trust-store-password: 123456
    #client-auth: need
    #trust-store-type: JKS
    #trust-store-provider: SUN

spring:
  application:
    name: boot
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/boot?useUnicode=true&useSSL=false&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
  redis:
    host: localhost
    password: 123456
    port: 6379

mybatis:
  type-aliases-package: com.d.entity
  configuration.map-underscore-to-camel-case: true
logging:
  config: classpath:logback-spring.xml
  path: /logs/${spring.application.name}_${server.port}
  level:
    com.d: info
    com.d.mapper: debug
---
spring.profiles: prod
logging:
  level:
    com.d.mapper: info
---
