server:
  port: 8090

spring:
  application:
    name: boot
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/boot?useUnicode=true&useSSL=false&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
  redis:
    host: localhost
    password: 123456
    port: 6379

#schedule
schedule.every.ten.minutes: 0/600 * * * * *

mybatis:
  type-aliases-package: com.d.entity
  configuration.map-underscore-to-camel-case: true
logging:
  config: classpath:logback-spring.xml
  path: /logs/${spring.application.name}_${server.port}
  level:
    com.d.web: info
    com.d.mapper: debug
---
spring.profiles: prod
logging:
  level:
    com.d.web: info
    com.d.mapper: info
---
